# Generated by Django 5.2.4 on 2025-08-20 18:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('books', '0002_alter_book_author_delete_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookVector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vector', models.BinaryField()),
                ('book', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vector', to='books.book')),
            ],
        ),
    ]
