# Generated by Django 5.2.5 on 2025-08-21 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0002_viewedbook'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ViewedBook',
        ),
    ]
