# Generated by Django 5.2.5 on 2025-08-21 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0003_delete_viewedbook'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookvector',
            old_name='vector',
            new_name='vector_data',
        ),
    ]
