# Generated by Django 5.2.5 on 2025-08-21 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0004_rename_vector_bookvector_vector_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookvector',
            old_name='vector_data',
            new_name='vector',
        ),
    ]
