# Generated by Django 5.2.5 on 2025-08-21 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0006_sessionbookview_usersession_sessionbookview_session_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersession',
            name='viewed_books',
        ),
        migrations.AlterUniqueTogether(
            name='userbookview',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='userbookview',
            name='book',
        ),
        migrations.RemoveField(
            model_name='userbookview',
            name='user',
        ),
        migrations.DeleteModel(
            name='SessionBookView',
        ),
        migrations.DeleteModel(
            name='UserSession',
        ),
        migrations.DeleteModel(
            name='UserBookView',
        ),
    ]
