# Generated by Django 5.2.5 on 2025-08-22 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0008_usersession_sessionbookview'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usersession',
            options={'ordering': ['-updated_at']},
        ),
    ]
