# Generated by Django 5.2.5 on 2025-08-22 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0009_alter_usersession_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersession',
            name='user',
        ),
        migrations.DeleteModel(
            name='SessionBookView',
        ),
        migrations.DeleteModel(
            name='UserSession',
        ),
    ]
